#!/usr/bin/env bun

// Generate Codex-native skill adapters from the canonical agent-skills source.
// Generated files are checked in so Codex's installed plugin cache is complete;
// this script and the canonical skills remain the only authoring surfaces.

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

export const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const sourceRoot = join(repoRoot, 'agent-skills');
const defaultOutputRoot = join(repoRoot, 'plugins', 'recall', 'skills');

export const routes: Record<string, string> = {
  'recall-add': 'Prefer the `memory_add` MCP tool. Use the CLI examples below only when the MCP server is unavailable.',
  'recall-doctor': 'This remains a local CLI diagnostic. Run `recall doctor`; the Codex plugin does not rewrite Codex-owned configuration.',
  'recall-dump': 'Use the `memory_dump` MCP tool with `source: "codex"` and explicit visible `messages`. MCP does not expose lifecycle auto-capture or a supported Codex transcript path.',
  'recall-loa': 'Prefer `loa_show` for a known entry and `memory_recall` to browse recent entries. Use CLI-only quote/list variants when needed.',
  'recall-recent': 'Prefer `memory_recall` for recent cross-table context. Use the CLI when an exact table-specific recent listing is required.',
  'recall-scout': 'Use the plugin MCP tools `memory_search`, `memory_hybrid_search`, and `context_for_agent` for the memory-first steps; keep the workflow sensitive-data boundary intact.',
  'recall-search': 'Prefer `memory_search`; use `memory_hybrid_search` for natural-language semantic retrieval. The CLI remains an explicit fallback.',
  'recall-stats': 'Prefer the `memory_stats` MCP tool. The CLI is an explicit fallback.',
  'recall-update': 'This remains check-only and CLI-backed. Never apply an update from an attached Codex session.',
};

export function addCodexRouting(source: string, route: string): string {
  source = source.replace(/^disable-model-invocation:\s*true\s*\n/m, '');
  const frontmatterEnd = source.indexOf('\n---', 4);
  if (!source.startsWith('---\n') || frontmatterEnd < 0) {
    throw new Error('canonical skill is missing YAML frontmatter');
  }
  const insertAt = frontmatterEnd + 4;
  const adapter = `\n\n<!-- Generated by scripts/build-codex-plugin.ts; do not edit. -->\n\n## Codex routing\n\n${route}\n\nThe canonical workflow below remains authoritative, but equivalent behavior is not assumed across hosts.\n`;
  return source.slice(0, insertAt) + adapter + source.slice(insertAt).replace(/^\n+/, '\n');
}

export function generateCodexPluginSkills(outputRoot: string = defaultOutputRoot): string[] {
  mkdirSync(outputRoot, { recursive: true });
  const skillNames = readdirSync(sourceRoot).filter(name => existsSync(join(sourceRoot, name, 'SKILL.md'))).sort();
  for (const name of skillNames) {
    const route = routes[name];
    if (!route) throw new Error(`missing Codex route for ${name}`);
    const source = readFileSync(join(sourceRoot, name, 'SKILL.md'), 'utf-8');
    const outputDir = join(outputRoot, name);
    mkdirSync(outputDir, { recursive: true });
    writeFileSync(join(outputDir, 'SKILL.md'), addCodexRouting(source, route));
    if (name === 'recall-dump') {
      const metadataDir = join(outputDir, 'agents');
      mkdirSync(metadataDir, { recursive: true });
      writeFileSync(
        join(metadataDir, 'openai.yaml'),
        'interface:\n  display_name: "Recall Dump"\n  short_description: "Explicitly save visible conversation messages"\npolicy:\n  allow_implicit_invocation: false\n',
      );
    }
  }
  const generated = readdirSync(outputRoot).filter(name => existsSync(join(outputRoot, name, 'SKILL.md'))).sort();
  if (generated.join('\n') !== skillNames.join('\n')) {
    throw new Error('generated Codex skill set contains stale or missing entries');
  }
  return skillNames;
}

if (import.meta.main) {
  console.log(`Generated ${generateCodexPluginSkills().length} Codex skill adapters.`);
}
